### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'extract'

### ISSUE THREAD

**Issue by mforthman** [RemiAllio/MitoFinder#1]
Hi,

I've been running mitofinder on 294 samples, using our own assemblies (-a option) and the program has largely been successful. However, I have 4 samples that keep throwing "AttributeError: 'NoneType' object has no attribute 'extract'". I cannot seem to pinpoint what is specifically causing the issue, but am curious if there are suggestions on what I can try.

/apps/mitofinder/1.0.2/Bio/GenBank/__init__.py:1096: BiopythonParserWarning: Couldn't parse feature location: '-2..238'
  % (location_line)))
Traceback (most recent call last):
  File "/apps/mitofinder/1.0.2/mitofinder", line 1264, in <module>
    out_fasta.write(str(feature.extract(record).seq) + '\n')
  File "/apps/mitofinder/1.0.2/Bio/SeqFeature.py", line 339, in extract
    return self.location.extract(parent_sequence)
AttributeError: 'NoneType' object has no attribute 'extract'

**Comment by RemiAllio** [comment]
Hi Michael,

Really happy to learn that MitoFinder works for you and can help you in your research.

Indeed, I observed this error before and, normally, I made a release to correct it few days ago. So, first of all,  I recommend that you download MitoFinder again (sorry for that) or replace the file named "genbankOutput.py" in your MitoFinder directory with the new file "genbankOutput.py" from the Github repository.
Please, tell me if this fixes the problem. 

Best regards,

Rémi Allio

**Comment by mforthman** [comment]
Hi Rémi,

Thank you so much for the suggestion. That took care of the problem we experienced.  Awesome bioinformatic package.

Cheers, Michael
