### ISSUE TITLE
Error while annotating assembled mitochondrion

### ISSUE THREAD

**Issue by kimnegrette3** [RemiAllio/MitoFinder#11]
Hi! 
I have an assembled mitochondrion from a microalgae (Scenedesmaceae). I was trying to annotate it with this command line:

mitofinder -j Sdimorphus -a mt_Sdim_flye_consensus.fasta -r mitochondrions_sphaeropleales_refseq.gb -o 22

But I got this error:

Traceback (most recent call last):
  File "/home/kim/MitoFinder/mitofinder", line 635, in <module>
    geneOut=open("ref_"+name+"_database.fasta",'a')
IOError: [Errno 2] No such file or directory: 'ref_hypotheticalreversetranscriptase/maturase_database.fasta'

I guess it has something to do with the reference file? I downloaded a genbank file directly from NCBI using "mitochondrion" AND "sphaeropleales" search terms and filtering by RefSeq and sequence length, as described [here](https://github.com/RemiAllio/MitoFinder#how-to-get-reference-mitochondrial-genomes-from-ncbi).

I appreciate any suggestions.

Thank you very much!

**Comment by RemiAllio** [comment]
Hi!

Thank you for your comment.

It seems that in your reference, there is at least one gene name with a "/" inside. 
In this precise case that is : "hypothetical reverse transcriptase/maturase"

To avoid this issue, you just need to remove/replace the "/" in the gene name (in the genbank file).
Sorry for the inconvenience. Your issue will be taken into account for the next version of MitoFinder.

Thank you,
Cheers,
Rémi

**Comment by kimnegrette3** [comment]
Thank you for your prompt answer. That solved the problem! 
Many thanks, and best regards!

**Comment by RemiAllio** [comment]
Hi!

This bug has been taken into account for the new version of MitoFinder ([v1.4](https://github.com/RemiAllio/MitoFinder#mitofinder-version-14))

Thanks again!
Rémi
