### ISSUE TITLE
tRNA annotation

### ISSUE THREAD

**Issue by AlesBucek** [RemiAllio/MitoFinder#12]
Dear Remi,
I'm using your MitoFinder for annotation of termite mitochondrial genomes and I'm super-satisfied. With a large reference database of termite mtGenomes it outperforms in my hands both Mitos and MitoZ for protein coding and rRNA genes.

However, I found that the tRNA predictions are rather poor (compared to manual annotation or to the two pipelines above).
I tested your annotation pipeline using 40 published termite mtGenomes (KP026260-KP026298). MitoFinder predicted on average 16 tRNAs per genome (out of 22) while the other two pipelines were above 21 average predicted tRNAs per genome. 
The summary stats of annotated tRNAs for the 40 genomes are below, showing the total number of each predicted tRNA among the 40 genomes. The summary stats shows also fuzzy naming of tRNAs:  there should be a single tRNA copy except for tRNA-Leu1/2 and tRNA-Ser1/2. 

    34 Name=tRNA-Ala 
      3 Name=tRNA-Ala2 
     34 Name=tRNA-Arg 
      2 Name=tRNA-Arg2 
     31 Name=tRNA-Asn 
      6 Name=tRNA-Asn2 
     38 Name=tRNA-Asp 
      1 Name=tRNA-Asp2 
     38 Name=tRNA-Gln 
     35 Name=tRNA-Glu 
     34 Name=tRNA-Gly 
      3 Name=tRNA-Gly2 
     31 Name=tRNA-His 
      7 Name=tRNA-His2 
     29 Name=tRNA-Ile 
     37 Name=tRNA-Leu 
      1 Name=tRNA-Leu2 
     36 Name=tRNA-Lys 
      1 Name=tRNA-Lys2 
     38 Name=tRNA-Met 
      1 Name=tRNA-Met2 
     35 Name=tRNA-Phe 
     35 Name=tRNA-Pro 
      2 Name=tRNA-Pro2 
     33 Name=tRNA-Ser 
     17 Name=tRNA-Ser2 
     34 Name=tRNA-Thr 
      4 Name=tRNA-Thr2 
      1 Name=tRNA-Trp 
      2 Name=tRNA-Trp2 
     35 Name=tRNA-Tyr 
      3 Name=tRNA-Tyr2 
     12 Name=tRNA-Val 
      4 Name=tRNA-Val2

I'm wondering, is there anything which can be done from within the MitoFinder pipeline to tune the performance of ARWEN module for tRNA annotation? 
Thanks in advance and best regards,
Ales

**Comment by RemiAllio** [comment]
Hi Ales,

Thank you for your feedback!

I need to work in a new version of MitoFinder to improve the tRNA annotation step. I hope I will have time soon, but at the moment nothing can be done to improve the performance of ARWEN module, unless you know of specific options of ARWEN that might help the annotation in your case (termites). In that case, I can help you to modify MitoFinder for your case. 

Anyway, as I said, I will update MitoFinder as soon as possible to improve the tRNA annotation step.

Cheers,
Rémi

**Comment by AlesBucek** [comment]
Hi Rémi,
thanks for the quick reply! I checked ARWEN briefly and I do not see anything which could improve it. I will use MitFi for annotation of tRNAs for now and will be looking forward for the next MitoFinder version.

Thanks and cheers,
Ales

**Comment by RemiAllio** [comment]
Hi Ales,

The new version of MitoFinder ([v1.4](https://github.com/RemiAllio/MitoFinder#mitofinder-version-14)) is out!
I added MiTFi (default) and tRNAscan-SE for the tRNA annotation step. 

Thanks again for your feedback!
Cheers,
Rémi

**Comment by AlesBucek** [comment]
Hi Rémi,
thanks for the notification; awesome job! I was using now mitfi separately but it is much more convenient to have everything in one pipeline. Cheers! A
