### ISSUE TITLE
Annotation with MitFi fails (v1.4)

### ISSUE THREAD

**Issue by MareikeJaniak** [RemiAllio/MitoFinder#14]
Hi Rémi, hi Frederic, 

I thought it would be better to put this in a new issue. I downloaded version 1.4 and ran MitoFinder on the test_case files. 

It looks like the annotation step fails, but I'm not sure why. I'm attaching the stdout file and the geneChecker.log. 

The file geneChecker_error.log has the following message:

ln: failed to create symbolic link './cmsearch': File exists
Traceback (most recent call last):
  File "/home/mcj43/software/MitoFinder/geneChecker_fasta.py", line 452, in <module>
    tRNAs = assemblyCheck.tRNAs
AttributeError: 'bool' object has no attribute 'tRNAs'

Let me know if you need anything else!

Best, 
Mareike

[geneChecker.log.txt](https://github.com/RemiAllio/MitoFinder/files/5339427/geneChecker.log.txt)
[test_MitoFinder.out.txt](https://github.com/RemiAllio/MitoFinder/files/5339428/test_MitoFinder.out.txt)

**Comment by RemiAllio** [comment]
Hi Mareike,

Thank you for your feedback. 
In fact, it seems that the tRNA annotation step failed.

Could you please check if the file [SeqID]_mitfi/*.mitfi exists and if mitfi found some hits ?
If not, do you have java installed in the computer running MitoFinder ?

Thank you,
Best,
Rémi

**Comment by MareikeJaniak** [comment]
Hi Rémi, 

I don't see a directory that is [SeqID]_mitfi. 

The following file exists but it is empty:
[SeqID]/[SeqID]_MitoFinder_megahit_mitfi_Final_Results/[SeqID]_mtDNA_contig.mitfi

Yes, I do have java installed. 

Let me know if I should try anything else!

Best, 
Mareike

**Comment by RemiAllio** [comment]
Hi Mareike,

Well, I don't know what happened, sorry about that!

Just to be sure I have all the elements to think about it, could you please:
- confirm that you downloaded MitoFinder with git clone ?
- confirm that you run the install.sh ?
- tell me if something is written in the geneChecker_error.txt file
- and eventually, run ```java -jar path/to/MitoFinder/mitfi/mitfi.jar [SeqID]_link.scafSeq```

Thank you so much and sorry for the inconvenience...
Best,
Rémi

**Comment by MareikeJaniak** [comment]
Hi Rémi, 

Sorry for the delay, I just saw your response. 

Yes, I downloaded MitoFinder with git clone and ran install.sh. 

The geneChecker_error.log file contains the following:

ln: failed to create symbolic link './cmsearch': File exists
Traceback (most recent call last):
  File "/home/mcj43/software/MitoFinder/geneChecker_fasta.py", line 452, in <module>
    tRNAs = assemblyCheck.tRNAs
AttributeError: 'bool' object has no attribute 'tRNAs'

When I run the java -jar line, I get the following error:

MiTFi - mitochondrial tRNA finder v0.1
Exception in thread "main" java.io.IOException: Cannot run program "./infernal-1.0.2/src/cmsearch": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:589)
	at java.base/java.lang.Runtime.exec(Runtime.java:413)
	at java.base/java.lang.Runtime.exec(Runtime.java:310)
	at mitfi.Main.main(Main.java:228)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:319)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:250)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 5 more

Maybe this has something to do with the first line of the geneChecker_error.log? I hope this helps!

Best, 
Mareike

**Comment by MareikeJaniak** [comment]
Hello again!

The problem seems to be solved! It was indeed an issue with java. I was sending the MitoFinder command out as jobs on our cluster and I didn't load the java module within the job scripts, because it's usually not necessary. 

I just tried it again with the java module loaded within the job script and it ran without issues!

Sorry for not realizing that sooner. My fault!

Best, 
Mareike

**Comment by RemiAllio** [comment]
Hi Mareike!

Thank you for the update. 
I will see how I can improve the error/log files to help the users to find what happened!
Let us know if MiTFi find similar or better results than tRNAscan-SE 2!

Best,
Rémi
