### ISSUE TITLE
Continue stopped assembly job

### ISSUE THREAD

**Issue by chezus666** [RemiAllio/MitoFinder#15]
Hi all,
thanks for the nice piece of software! I had an assembly running, which was stopped because I did not allocate enough memory. I used metaspades as assembler which has the option "--continue" to continue started jobs, and I was wondering if there is a way to tell Mitofinder to tell metaspades to use this option. Or generally how can I change parameters in the programs Mitofinder uses.

Cheers!

**Comment by RemiAllio** [comment]
Hi,

I didn't know that it was possible to continue a stopped assembly with metaSPAdes. So there is no option within MitoFinder for this (good point for the next version, thanks!).
However, I think the easiest way to continue the stopped assembly is to use metaSPAdes separately and then give the resulted assembly to MitoFinder with the ```-a``` option.

So, you can use the ```metaspades.py``` of the MitoFinder repository: ```path/to/MitoFinder/metaspades/bin/metaspades.py```
with the specific options to continue the assembly.
The output folder of metaSPAdes to specify for this option should be named ```[SeqID]_metaspades``` in the output folder of MitoFinder,

Once the assembly is completed, you can run MitoFinder again with the ```-a``` option by specifying the result of metaSPAdes as input assembly.

I hope this helps,
Cheers,
Rémi

**Comment by chezus666** [comment]
Hi,
okay thanks for the fast reply! I will try that.

Cheers!

**Comment by RemiAllio** [comment]
Hi, 

Let me know if it works or if you have any problems.

Cheers,
Rémi

**Comment by chezus666** [comment]
Hi,
I made some changes to the dataset, therefore I had to rerun it anyway, so I didnt try your suggestion after all. But generally I think it would be cool if there would be an easy option to adress the parameters of the assemblers Mitofinder uses.
Cheers!

**Comment by RemiAllio** [comment]
Hi,

All right. 
I agree, I have to think about how to implement it for the next version of MitoFinder!

Thank you for your feedback,

Cheers,
Rémi
