### ISSUE TITLE
When run Mitofinder met a problem

### ISSUE THREAD

**Issue by kuangzhuoran** [RemiAllio/MitoFinder#18]
Traceback (most recent call last):
  File "/data/01/user164/workspace/try/MitoFinder/mitofinder", line 1205, in <module>
    rename = Popen(args1, stdout=open(os.devnull, 'wb'))
  File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

upon is the error,and i also attach the log file
[Mf_MitoFinder.log](https://github.com/RemiAllio/MitoFinder/files/5897283/Mf_MitoFinder.log)

I dont know what should  i  do
Thank u so much

**Comment by RemiAllio** [comment]
Hi,

Thank you for your message.

Please, could you give me more information about the system in which you are running MitoFinder (Linux/MAC/Windows)?
Also, what is your default python environment? python2.7 ?

Cheers,
Rémi

**Comment by kuangzhuoran** [comment]
Hi ! Thanks for replying. I  run mitofinder on Linux(Xshell), default python is python3.7, but I have also installed py2.7

First error I met is "bad interpreter: user/bin/python: no such file or directory";  so I "vim   mitofinder/rename_fasta_seqID.py", and I change the first line"usr/bin/python"(python3.7) to "usr/bin/python2"(python2.7)

I have resolved the above problem, maybe. the error is on line 1205, I add "shell = True"  in parentheses，like " Popen(args1,  shell=True, stdout=open(os.devnull, 'wb'))".  And I rerun mitofinder, the error is the same, but  on different line, Repeat this  until no error is reported .

Now I meet a new error, like

Traceback (most recent call last):
  File "/data/01/user164/workspace/try/MitoFinder/mitofinder", line 1337, in <module>                                    
    if check_if_string_in_file(pathtowork + "/geneChecker.log","MiTFi failed.") or (os.stat(pathOfFinalResults+"MiTFi.log").st_size != 0 and not check_if_string_in_file(pathOfFinalResults+"MiTFi.log","hits")) :     
                            
OSError: [Errno 2] No such file or directory: '/data/01/user164/workspace/mito_test/mito_test_MitoFinder_mitfi_Final_Results/MiTFi.log'


[MitoFinder.log](https://github.com/RemiAllio/MitoFinder/files/5938396/MitoFinder.log)

**Comment by kuangzhuoran** [comment]
> Hi,
> 
> I am really sorry for the delay...
> 
> Since the installation seems to be complexe in your environment, I would like to try something else.
> I am trying to develop a MitoFinder image using [Singularity](https://sylabs.io/docs/).
> 
> I have built an image for you and you should be able to download it here:
> [MitoFinder_1.4.sif](https://filesender.renater.fr/?s=download&token=c337e424-d28f-4e1f-862a-b94db2024b47)
> 
> This is a temporary link, but if it works for you, I will make it permanent for everyone.
> 
> The only thing you need to do is to install singularity (it should work using `sudo apt install singularity`. If not, you should find out how to install it [here](https://sylabs.io/docs/)).
> Then, you should be able to run mitofinder as follows:
> 
> `PATH/TO/MitoFinder_1.4.sif -j [seqid] -1 [left_reads.fastq.gz] -2 [right_reads.fastq.gz] -r [genbank_reference.gb] -o [genetic_code] -p [threads] -m [memory]`
> 
> Please, tell me if it works and if you found it easy to run.
> Best regards,
> Rémi



Hi ! Thank you for your help!
I am so sry I dont reply in time

I have tried this  now, I use "conda install singularity" to install singularity,because I dont have root / permission.  And I met a ERROR, I have tried this in python3.8 and python3.7

ERROR  : Unknown image format/type: ./MitoFinder_1.4.sif
ABORT  : Retval = 255
 
I m try to solve this

**Comment by kuangzhuoran** [comment]
Hi ! Thank you for your help!
I am so sry I dont reply in time

I have tried this now, I use "conda install singularity" to install singularity,because I dont have root / permission. And I met a ERROR, I have tried this in python3.8 and python3.7

ERROR : Unknown image format/type: ./MitoFinder_1.4.sif
ABORT : Retval = 255

I m try to solve this

**Comment by RemiAllio** [comment]
Hi,

So, just to be sure: when you run ```singularity --version``` the command works and give you the version of singularity installed?
Then, when you try ```./MitoFinder_1.4.sif``` from the directory containing the program, you have the error, right?

**Comment by kuangzhuoran** [comment]
Hi !
yes~
singularity -v
Increasing verbosity level (2)
Singularity version: 2.4.2-dist

**Comment by RemiAllio** [comment]
Hi!

All right, it seems that you have installed a really old version of singularity. The issue may come from that.
Could you install a more recent version?  I'm afraid you'll probably have to ask someone who has permission to install it ([install singularity](https://sylabs.io/guides/3.0/user-guide/installation.html)).

Tell me if it is possible and if it works. 
Sorry for the inconvenience.

Best regards,
Rémi

**Comment by kuangzhuoran** [comment]
Hi ! so sorry
I have asked the administrator to help me install this software， but he told me that He tried for a long time and couldn't install it。
I will try on another server。

**Comment by kuangzhuoran** [comment]
Hi !  
After I changed the server and installed singularity correctly, it can work normally.
Thanks for your help!!!!!

Best Regards,
kzr

**Comment by RemiAllio** [comment]
Hi!

Thank you for the good news!
I am very happy that it works for you.

The singularity container is now available [here](https://github.com/RemiAllio/MitoFinder_container#singularity-container-for-mitofinder-version-14)!

Best regards,
Rémi
