### ISSUE TITLE
Can't install MitoFinder

### ISSUE THREAD

**Issue by Flowmatics** [RemiAllio/MitoFinder#2]
Hi, 

I am quite thrilled about MitoFinder and wanted to install this week. Unfortunately I got an error. It is strange. Apparently the script is looking for something which is not there. I tried to fix it with a colleague but we were not able to get it running. Can you help us? 
Please find the log below:

florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ ./install.sh 
./build.sh: line 1: aclocal: command not found
./build.sh: line 2: autoconf: command not found
./build.sh: line 3: automake: command not found
./build.sh: line 4: ./configure: No such file or directory
make: *** No rule to make target 'clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ cat install.sh 
chmod 764 */*/*/*
chmod 764 */*/*
chmod 764 */*
chmod 764 *
cd  idba
./build.sh
cd ..
cd metaSpades/bin/
p=$(pwd)
ln -s "$p"/spades.py "$p"/metaspades.py
cd ../../
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ cd idba/
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba$ ls
aclocal.m4  build.sh     configure.ac  install-sh   NEWS       stamp-h1
AUTHORS     ChangeLog    depcomp       lib          README.md  test
bin         config.h     Dockerfile    Makefile.am  script     WORKSPACE
BUILD       config.h.in  gtest_src     missing      src
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba$ ./build.sh 
./build.sh: line 1: aclocal: command not found
./build.sh: line 2: autoconf: command not found
./build.sh: line 3: automake: command not found
./build.sh: line 4: ./configure: No such file or directory
make: *** No rule to make target 'clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba$ cd..
cd..: command not found
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba$ ls
aclocal.m4  build.sh     configure.ac  install-sh   NEWS       stamp-h1
AUTHORS     ChangeLog    depcomp       lib          README.md  test
bin         config.h     Dockerfile    Makefile.am  script     WORKSPACE
BUILD       config.h.in  gtest_src     missing      src
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba$ cd ..
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ ls
Bio                              megahit
blast                            metaSpades
CHANGELOG                        mitofinder
circularizationCheck.py          Mitofinder.config
circularizationCheck.pyc         README.md
export_mitochondrial_contigs.py  rename_fasta_seqID.py
extract_genes.py                 runIDBA.py
extract_seq.py                   runIDBA.pyc
FirstBuildChecker.py             runMegahit.py
FirstBuildChecker.pyc            runMegahit.pyc
genbankOutput.py                 runMetaspades.py
genbankOutput.pyc                runMetaspades.pyc
geneChecker_fasta.py             sort_gff.py
geneChecker.py                   testcase
geneChecker.pyc                  tRNAscan
idba                             tRNAscanChecker_arwen.py
image                            tRNAscanChecker.py
install.sh                       tRNAscanChecker.pyc
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ make clean
make: *** No rule to make target 'clean'.  Stop.
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ make
make: *** No targets specified and no makefile found.  Stop.
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ cd Bio/
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/Bio$ ls
Affy                FSSP                   NeuralNetwork      SeqRecord.py
Align               GA                     Nexus              SeqRecord.pyc
AlignIO             GenBank                NMR                Sequencing
Alphabet            Geo                    pairwise2.py       SeqUtils
Application         Graphics               ParserSupport.py   Statistics
bgzf.py             HMM                    ParserSupport.pyc  SubsMat
bgzf.pyc            HotRand.py             Pathway            SVDSuperimposer
Blast               Index.py               PDB                SwissProt
CAPS                __init__.py            Phylo              TogoWS
Cluster             __init__.pyc           PopGen             trie.c
Compass             KDTree                 _py3k              triefind.py
cpairwise2module.c  KEGG                   Restriction        trie.h
Crystal             kNN.py                 SCOP               triemodule.c
Data                LogisticRegression.py  SearchIO           UniGene
DocSQL.py           MarkovModel.py         Search.py          UniProt
Emboss              MaxEntropy.py          SeqFeature.py      _utils.py
Entrez              Medline                SeqFeature.pyc     _utils.pyc
ExPASy              Motif                  SeqIO              Wise
File.py             motifs                 Seq.py
File.pyc            NaiveBayes.py          Seq.pyc
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/Bio$ cd ..
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ ls
Bio                              megahit
blast                            metaSpades
CHANGELOG                        mitofinder
circularizationCheck.py          Mitofinder.config
circularizationCheck.pyc         README.md
export_mitochondrial_contigs.py  rename_fasta_seqID.py
extract_genes.py                 runIDBA.py
extract_seq.py                   runIDBA.pyc
FirstBuildChecker.py             runMegahit.py
FirstBuildChecker.pyc            runMegahit.pyc
genbankOutput.py                 runMetaspades.py
genbankOutput.pyc                runMetaspades.pyc
geneChecker_fasta.py             sort_gff.py
geneChecker.py                   testcase
geneChecker.pyc                  tRNAscan
idba                             tRNAscanChecker_arwen.py
image                            tRNAscanChecker.py
install.sh                       tRNAscanChecker.pyc
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ ./install.sh 
./build.sh: line 1: aclocal: command not found
./build.sh: line 2: autoconf: command not found
./build.sh: line 3: automake: command not found
./build.sh: line 4: ./configure: No such file or directory
make: *** No rule to make target 'clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
ln: failed to create symbolic link '/home/florian/Downloads/MitoFinder-master/metaSpades/bin/metaspades.py': File exists
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ emacs install.sh -nwflorian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ which bash
/bin/bash
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ emacs install.sh -nwflorian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ ./install.sh
bash: ./install.sh: /usr/bin/bash: bad interpreter: No such file or directory
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ emacs install.sh -nwflorian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ ./install.sh
./build.sh: line 1: aclocal: command not found
./build.sh: line 2: autoconf: command not found
./build.sh: line 3: automake: command not found
./build.sh: line 4: ./configure: No such file or directory
make: *** No rule to make target 'clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
ln: failed to create symbolic link '/home/florian/Downloads/MitoFinder-master/metaSpades/bin/metaspades.py': File exists
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ cat install.sh
#!/bin/bash

chmod 764 */*/*/*
chmod 764 */*/*
chmod 764 */*
chmod 764 *
cd  idba
./build.sh
cd ..
cd metaSpades/bin/
p=$(pwd)
ln -s "$p"/spades.py "$p"/metaspades.py
cd ../../
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ ls
Bio                              megahit
blast                            metaSpades
CHANGELOG                        mitofinder
circularizationCheck.py          Mitofinder.config
circularizationCheck.pyc         README.md
export_mitochondrial_contigs.py  rename_fasta_seqID.py
extract_genes.py                 runIDBA.py
extract_seq.py                   runIDBA.pyc
FirstBuildChecker.py             runMegahit.py
FirstBuildChecker.pyc            runMegahit.pyc
genbankOutput.py                 runMetaspades.py
genbankOutput.pyc                runMetaspades.pyc
geneChecker_fasta.py             sort_gff.py
geneChecker.py                   testcase
geneChecker.pyc                  tRNAscan
idba                             tRNAscanChecker_arwen.py
image                            tRNAscanChecker.py
install.sh                       tRNAscanChecker.pyc
install.sh~
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ cd idba/
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba$ ls
aclocal.m4  build.sh     configure.ac  install-sh   NEWS       stamp-h1
AUTHORS     ChangeLog    depcomp       lib          README.md  test
bin         config.h     Dockerfile    Makefile.am  script     WORKSPACE
BUILD       config.h.in  gtest_src     missing      src
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba$ ./config.h
./config.h: line 1: /bin: Is a directory
./config.h: line 2: /bin: Is a directory
./config.h: command substitution: line 4: unexpected EOF while looking for matching `''
./config.h: command substitution: line 14: syntax error: unexpected end of file
./config.h: line 4: /bin: Is a directory
./config.h: line 73: unexpected EOF while looking for matching `''
./config.h: line 75: syntax error: unexpected end of file
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba$ lsls

Command 'lsls' not found, did you mean:

  command 'fsls' from deb python-fs
  command 'lsns' from deb util-linux

Try: sudo apt install <deb name>

florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba$ ls
aclocal.m4  bin    build.sh   config.h     configure.ac  Dockerfile  install-sh  Makefile.am  NEWS       script  stamp-h1  WORKSPACE
AUTHORS     BUILD  ChangeLog  config.h.in  depcomp       gtest_src   lib         missing      README.md  src     test
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba$ ./configure
bash: ./configure: No such file or directory
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba$ less install-sh 
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba$ less README.md 
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba$ ./configure.ac 
./configure.ac: line 4: syntax error near unexpected token `2.59'
./configure.ac: line 4: `AC_PREREQ(2.59)'
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba$ ./configure
bash: ./configure: No such file or directory
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba$ make
make: *** No targets specified and no makefile found.  Stop.
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba$ ls
aclocal.m4  bin    build.sh   config.h     configure.ac  Dockerfile  install-sh  Makefile.am  NEWS       script  stamp-h1  WORKSPACE
AUTHORS     BUILD  ChangeLog  config.h.in  depcomp       gtest_src   lib         missing      README.md  src     test
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba$ less install-sh 
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba$ ./install-sh 
./install-sh: no input file specified.
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba$ cd bin/
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba/bin$ ls
Makefile.am
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba/bin$ make
make: *** No targets specified and no makefile found.  Stop.
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba/bin$ ls
Makefile.am
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba/bin$ cd ..
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba$ ls
aclocal.m4  bin    build.sh   config.h     configure.ac  Dockerfile  install-sh  Makefile.am  NEWS       script  stamp-h1  WORKSPACE
AUTHORS     BUILD  ChangeLog  config.h.in  depcomp       gtest_src   lib         missing      README.md  src     test
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba$ cd src/
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba/src$ ls
assembly  basic  container  graph  misc  release  sequence  test  tools
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba/src$ cd ..
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba$ l
saclocal.m4*  BUILD*      config.h*      depcomp*     install-sh*   missing*    script/    test/
AUTHORS*     build.sh*   config.h.in*   Dockerfile*  lib/          NEWS*       src/       WORKSPACE*
bin/         ChangeLog*  configure.ac*  gtest_src/   Makefile.am*  README.md*  stamp-h1*
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba$ less BUILD 
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba$ ls
aclocal.m4  bin    build.sh   config.h     configure.ac  Dockerfile  install-sh  Makefile.am  NEWS       script  stamp-h1  WORKSPACE
AUTHORS     BUILD  ChangeLog  config.h.in  depcomp       gtest_src   lib         missing      README.md  src     test
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/idba$ cd ..
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ ls
Bio                              FirstBuildChecker.py   image              rename_fasta_seqID.py  testcase
blast                            FirstBuildChecker.pyc  install.sh         runIDBA.py             tRNAscan
CHANGELOG                        genbankOutput.py       install.sh~        runIDBA.pyc            tRNAscanChecker_arwen.py
circularizationCheck.py          genbankOutput.pyc      megahit            runMegahit.py          tRNAscanChecker.py
circularizationCheck.pyc         geneChecker_fasta.py   metaSpades         runMegahit.pyc         tRNAscanChecker.pyc
export_mitochondrial_contigs.py  geneChecker.py         mitofinder         runMetaspades.py
extract_genes.py                 geneChecker.pyc        Mitofinder.config  runMetaspades.pyc
extract_seq.py                   idba                   README.md          sort_gff.py
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ make
make: *** No targets specified and no makefile found.  Stop.
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ ös
ös: command not found
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ ls
Bio                              FirstBuildChecker.py   image              rename_fasta_seqID.py  testcase
blast                            FirstBuildChecker.pyc  install.sh         runIDBA.py             tRNAscan
CHANGELOG                        genbankOutput.py       install.sh~        runIDBA.pyc            tRNAscanChecker_arwen.py
circularizationCheck.py          genbankOutput.pyc      megahit            runMegahit.py          tRNAscanChecker.py
circularizationCheck.pyc         geneChecker_fasta.py   metaSpades         runMegahit.pyc         tRNAscanChecker.pyc
export_mitochondrial_contigs.py  geneChecker.py         mitofinder         runMetaspades.py
extract_genes.py                 geneChecker.pyc        Mitofinder.config  runMetaspades.pyc
extract_seq.py                   idba                   README.md          sort_gff.py
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ cd ..
florian@florian-ThinkPad-P50:~/Downloads$ ls
Fake-Gelelektrophorese.pdf  MitoFinder-master  MitoFinder-master.zip
florian@florian-ThinkPad-P50:~/Downloads$ cd MitoFinder-master/
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ ls
Bio                              FirstBuildChecker.py   image              rename_fasta_seqID.py  testcase
blast                            FirstBuildChecker.pyc  install.sh         runIDBA.py             tRNAscan
CHANGELOG                        genbankOutput.py       install.sh~        runIDBA.pyc            tRNAscanChecker_arwen.py
circularizationCheck.py          genbankOutput.pyc      megahit            runMegahit.py          tRNAscanChecker.py
circularizationCheck.pyc         geneChecker_fasta.py   metaSpades         runMegahit.pyc         tRNAscanChecker.pyc
export_mitochondrial_contigs.py  geneChecker.py         mitofinder         runMetaspades.py
extract_genes.py                 geneChecker.pyc        Mitofinder.config  runMetaspades.pyc
extract_seq.py                   idba                   README.md          sort_gff.py
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ less CHANGELOG 
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ ls
Bio                              FirstBuildChecker.py   image              rename_fasta_seqID.py  testcase
blast                            FirstBuildChecker.pyc  install.sh         runIDBA.py             tRNAscan
CHANGELOG                        genbankOutput.py       install.sh~        runIDBA.pyc            tRNAscanChecker_arwen.py
circularizationCheck.py          genbankOutput.pyc      megahit            runMegahit.py          tRNAscanChecker.py
circularizationCheck.pyc         geneChecker_fasta.py   metaSpades         runMegahit.pyc         tRNAscanChecker.pyc
export_mitochondrial_contigs.py  geneChecker.py         mitofinder         runMetaspades.py
extract_genes.py                 geneChecker.pyc        Mitofinder.config  runMetaspades.pyc
extract_seq.py                   idba                   README.md          sort_gff.py
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ sh install.sh 
./build.sh: 1: ./build.sh: aclocal: not found
./build.sh: 2: ./build.sh: autoconf: not found
./build.sh: 3: ./build.sh: automake: not found
./build.sh: 4: ./build.sh: ./configure: not found
make: *** No rule to make target 'clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
ln: failed to create symbolic link '/home/florian/Downloads/MitoFinder-master/metaSpades/bin/metaspades.py': File exists
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ cd blast/
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/blast$ ls
bin  ChangeLog  doc  LICENSE  ncbi_package_info  README
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master/blast$ cd ..
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ ls
Bio                              FirstBuildChecker.py   image              rename_fasta_seqID.py  testcase
blast                            FirstBuildChecker.pyc  install.sh         runIDBA.py             tRNAscan
CHANGELOG                        genbankOutput.py       install.sh~        runIDBA.pyc            tRNAscanChecker_arwen.py
circularizationCheck.py          genbankOutput.pyc      megahit            runMegahit.py          tRNAscanChecker.py
circularizationCheck.pyc         geneChecker_fasta.py   metaSpades         runMegahit.pyc         tRNAscanChecker.pyc
export_mitochondrial_contigs.py  geneChecker.py         mitofinder         runMetaspades.py
extract_genes.py                 geneChecker.pyc        Mitofinder.config  runMetaspades.pyc
extract_seq.py                   idba                   README.md          sort_gff.py
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ less Mitofinder.config 
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ less mitofinder 
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ ls
Bio                              FirstBuildChecker.py   image              rename_fasta_seqID.py  testcase
blast                            FirstBuildChecker.pyc  install.sh         runIDBA.py             tRNAscan
CHANGELOG                        genbankOutput.py       install.sh~        runIDBA.pyc            tRNAscanChecker_arwen.py
circularizationCheck.py          genbankOutput.pyc      megahit            runMegahit.py          tRNAscanChecker.py
circularizationCheck.pyc         geneChecker_fasta.py   metaSpades         runMegahit.pyc         tRNAscanChecker.pyc
export_mitochondrial_contigs.py  geneChecker.py         mitofinder         runMetaspades.py
extract_genes.py                 geneChecker.pyc        Mitofinder.config  runMetaspades.pyc
extract_seq.py                   idba                   README.md          sort_gff.py
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$ sudo ./install.sh
./build.sh: line 1: aclocal: command not found
./build.sh: line 2: autoconf: command not found
./build.sh: line 3: automake: command not found
./build.sh: line 4: ./configure: No such file or directory
make: *** No rule to make target 'clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
ln: failed to create symbolic link '/home/florian/Downloads/MitoFinder-master/metaSpades/bin/metaspades.py': File exists
florian@florian-ThinkPad-P50:~/Downloads/MitoFinder-master$

**Comment by RemiAllio** [comment]
Hello,
Ok, it's a bit difficult for me to read your message (I don't understand why some lines are crossed out) but it seems that automake is not installed on your computer.
To install it you can run the following command:

sudo apt-get install automake

So,  please, could you install automake, rerun the installation, and tell me if it solved the installation problem.

Best regards,
Rémi

_N.B._: Given that the error is specific to IDBA-UD, you should be able to use MitoFinder with MetaSPAdes or MEGAHIT.

**Comment by Flowmatics** [comment]
Hi! Thank you for the quick response. Sorry for the strange crossed out lines, I don't know why it looks so strange. 
automake was really not installed, I tried it and problem is solved.

Thank you!
