### ISSUE TITLE
Unprivileged user installation of dependencies.

### ISSUE THREAD

**Issue by roguephysicist** [RemiAllio/MitoFinder#21]
Hi,

I am trying to install MitoFinder on a shared HPC system. Unfortunately, the following `make install` step from `install.sh`:

```
cd "$wd"/trnascanSE
tar -xvf infernal-1.1.3.tar.gz
cd infernal-1.1.3
./configure
make
make install
```

fails because the `--prefix` is not set to anything, thus defaulting to `/usr/local`. What should the correct prefix be?

Thanks.

**Comment by RemiAllio** [comment]
Hi,

Thank you for contacting me.

Could you try to specify ```--prefix=$(pwd)/exe``` in the install.sh file?
Please, let me know if it works,

Cheers,
Rémi

**Comment by roguephysicist** [comment]
Seems like it works. Thanks!
