### ISSUE TITLE
Mitochondrial contigs were detected after blast, but no results were written in to <Sample_ID>_mitfi_Final_Results folder

### ISSUE THREAD

**Issue by Menglinhsy** [RemiAllio/MitoFinder#23]
Hi Remi,

Recently, we found mitochondrial contigs were detected according to the blast results (IDXX_blast_ouT.txt), but no results were written into folder <Sample_ID>_mitfi_Final_Results.  

We assumed that it was probably because of some threshold settings. So is there any way to change the settings, or is there any other reasons? 

Here i attached one example. 

[73.txt](https://github.com/RemiAllio/MitoFinder/files/6613107/73.txt)

[73.zip](https://github.com/RemiAllio/MitoFinder/files/6613109/73.zip)

Best wishes,
Menglin

**Comment by RemiAllio** [comment]
Hi Menglin,

Could you please send me all the files generated by MitoFinder (log file + output directory)?
I am just wondering if MitoFinder finished the job.

If so, there are several options to deal with threshold setting:
```
-e BLASTEVAL, --blast-eval BLASTEVAL
                        e-value of blast program used for contig
                        identification and annotation. Default = 0.00001
--blast-identity-nucl BLASTIDENTITYNUCL
                        Nucleotide identity percentage for a hit to be
                        retained. Default = 50
--blast-identity-prot BLASTIDENTITYPROT
                        Amino acid identity percentage for a hit to be
                        retained. Default = 40
--blast-size ALIGNCUTOFF
                        Percentage of overlap in blast best hit to be
                        retained. Default = 30
```

Tell me if it helps,
Cheers,
Rémi

**Comment by Menglinhsy** [comment]
Hi, Remi,

Thanks for your reply and suggestions, I will try that. 

but which .py file should I go and change these parameters? 

here is all the output.

[73.zip](https://github.com/RemiAllio/MitoFinder/files/6623193/73.zip)

Best,
Menglin

**Comment by RemiAllio** [comment]
Hi Menglin,

Thank you for the files.
Indeed, MitoFinder didn't find mitochondrial contigs given the threshold used.
There is also a threshold for the size of the contig to be considered. By default, contigs smaller than 1000 bp are not considered. You can change this threshold using the following argument:

```
--contig-size-min CONTIGSIZEMIN
                        Minimum size of a contig to be considered. Default =
                        1000
```

To change the parameters you need to specify them in the command line.
For example:

```
mitofinder -j 73 -a 73.fasta -r sequence.gb -o 5 -p 10  --blast-eval 0.00001 --blast-identity-nucl 50 --blast-identity-prot 40 --blast-size 30 --contig-size-min 300
```

I hope this helps.
Best,
Rémi

**Comment by RemiAllio** [comment]
Hi Menglin,

Did my previous message help you?
Can I close this issue?

Best,
Rémi

**Comment by Menglinhsy** [comment]
Hi, Remi,

Sorry for the late reply. it works!

Thanks a lot!

Best,
Menglin

**Comment by RemiAllio** [comment]
Hi,

Great! I am happy we found the solution :-)

Best,
Rémi
