### ISSUE TITLE
ncbi-blast-2.12.0+/binmakeblastdb is not executable

### ISSUE THREAD

**Issue by jbernst** [RemiAllio/MitoFinder#24]
Hello,

I am trying to run MitoFinder on a mac OS Big Sur and have installed the dependencies needed to run MitoFinder (at least Metaspades, BLAST, and the tRNA annotation dependencies).

Currently I have MitoFinder as a directory by itself, and BLAST is outside of it. MitoFinder is in my path, as is blast. Every time I try to run MitoFinder, it says:
```
Now running MitoFinder ...

Start time : 2021-09-01 14:49:08

Job name = CS

Creating Output directory : /Users/name/PhyloPrograms/MitoTest/CS
All results will be written here

Program folders:
MEGAHIT = /Users/name/PhyloPrograms/MitoFinder/megahit/
MetaSPAdes folder = /Users/name/PhyloPrograms/SPAdes-3.14.0-Darwin/bin
IDBA-UD folder = /Users/name/PhyloPrograms/MitoFinder/idba/bin/
Blast folder = /Users/name/PhyloPrograms/ncbi-blast-2.12.0+/bin
ARWEN folder = /Users/name/PhyloPrograms/MitoFinder/arwen/
MiTFi folder = /Users/name/PhyloPrograms/MitoFinder/mitfi/
tRNAscan-SE folder = /Users/name/PhyloPrograms/MitoFinder/trnascanSE/tRNAscan-SE-2.0/

/Users/name/PhyloPrograms/ncbi-blast-2.12.0+/binmakeblastdb is not executable
Please check the installation and the path indicated above and restart MitoFinder.
Aborting 
```

I have tried removing the + sign from the ncbi-blast directory, I've tried moving the directory around, I have tried having 'default' as the path in the MitoFinder.config file, but no matter what I do, it things that 'bin' is part of the word 'makeblastdn'

Has anyone ever encountered this before? Do you know what the issue might be? Thank you!

Best,
Justin

**Comment by RemiAllio** [comment]
Hi Justin,

Thank you for contacting me.

It seems that the path to your blast folder is incomplete in the config file. 
Could you please try to add a "/" at the end of the path as follows ?

/Users/name/PhyloPrograms/ncbi-blast-2.12.0+/bin/

Same for MetaSPAdes:
/Users/name/PhyloPrograms/SPAdes-3.14.0-Darwin/bin/

Let me know if it works afterwards. I can adapt the script in the next version of MitoFinder to avoid this problem. 
Hope this message will help you!
Best,
Rémi

**Comment by jbernst** [comment]
That worked! I thought I tried that, but apparently not. Thanks so much for helping with this (easy) fix! I appreciate it.

Best,
Justin
