### ISSUE TITLE
git clone is now up to speed with git-lfs clone

### ISSUE THREAD

**Issue by sam217pa** [RemiAllio/MitoFinder#27]
Hi and thanks for MitoFinder!

Just wanted to let you know that I followed your instruction and got a warning message telling me that `git clone` now has comparable speed to `git lfs clone` (working with git 2.20.1, git lfs 1.5.2);
that should make the installation instruction for singularity a bit simpler.

cheers,

**Comment by RemiAllio** [comment]
Hi !

Thank you for your feedback!
I don't know if I can use ```git clone``` instead of ```git lfs clone``` since the size of the container is bigger than requested for ```git clone```. That's why I use ```git lfs clone```...
However, I will soon upload the MitoFinder container to the singularity cluster to allow it to be downloaded directly with singularity. I think this should make the installation much easier.

Best,
Rémi

**Comment by sam217pa** [comment]
Yes it will 👍 

Do you know about https://biocontainers.pro/tools/mitofinder?
They host both a docker and singularity image of mitofinder that seems to include dependencies as well (found megahit and metaspades.py, can't locate mitfi.jar though.).

I can try it out and let you know how it goes if that helps?

**Comment by RemiAllio** [comment]
Hi,

I had no idea about the container you mentioned. Do you know who created it? 
Do you think this biocontainer is used?

Here is the command to download the last singularity image of MitoFinder :-)
```singularity pull --arch amd64 library://remiallio/default/mitofinder:v1.4.1```

I will update the readme in the github as soon as possible.
Cheers,
Rémi

**Comment by sam217pa** [comment]
Excellent 👍 

I don't know who created it. From what I understand recipes pushed to bioconda (as is mitofinder https://anaconda.org/bioconda/mitofinder) are also deployed as containers thanks to the biocontainers continuous integration. The repo listed in the bioconda recipe is https://github.com/parklab/xTea though, which doesn't have anything to do with MitoFinder 🤔🤔
The biocontainer page say it was downloaded 565 times, so I guess it *is* used 👍 

cheers!

**Comment by sam217pa** [comment]
Just wanted to let you know that the singularity image you pushed worked flawlessly on pre-computed assemblies on my side.

Nice work!

**Comment by RemiAllio** [comment]
Nice! Thank you :slightly_smiling_face: 

Regarding your previous message:
This is quite strange! It is indeed downloaded enough to assume that it is used even though I don't know if this container actually works... 
I'm not sure I understand the connection with https://github.com/parklab/xTea either. :thinking:

Anyway, thanks for pointing it out to me :slightly_smiling_face:
