### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by qingjiaowohlj** [RemiAllio/MitoFinder#29]
Hello, sorry to disturb you, I install mitofinder following your README. but after I add the PATH, it still has such error:

peng@peng-System-Product-Name:~/mitofinder/MitoFinder$ mitofinder -v
  File "/home/peng/mitofinder/MitoFinder/mitofinder", line 148
    print "\n # For trimmed paired-end reads:\nmitofinder --megahit -j [seqid] \\\n\t-1 [left_reads.fastq.gz] \\\n\t-2 [right_reads.fastq.gz] \\\n\t-r [genbank_reference.gb] \\\n\t-o [genetic_code] \\\n\t-p [threads] \\\n\t-m [memory]\n\n # For trimmed single-end reads:\nmitofinder --megahit -j [seqid] \\\n\t-s [SE_reads.fastq.gz] \\\n\t-r [genbank_reference.gb] \\\n\t-o [genetic_code] \\\n\t-p [threads] \\\n\t-m [memory]\n\n # For one assembly (one or more contig(s))\nmitofinder -j [seqid] \\\n\t-a [assembly.fasta] \\\n\t-r [genbank_reference.gb] \\\n\t-o [genetic_code] \\\n\t-p [threads] \\\n\t-m [memory]\n"
          ^
SyntaxError: invalid syntax

It's the first installation.

**Comment by RemiAllio** [comment]
Hello,

Could you tell me which version of python are you using? It needs to be python 2.7.

Maybe you should install singularity as recommended in the [readme](https://github.com/RemiAllio/MitoFinder#run-mitofinder-with-singularity) and use the [MitoFinder container](https://cloud.sylabs.io/library/_container/61557b8a7163109769dfaf38). This is the easiest way to install and run MitoFinder.


Tell me if this helps, 
Best regards,
Rémi

**Comment by qingjiaowohlj** [comment]
Thank you for your replay,since I use the Python 2.7, the problem solved. Thank you very much.

**Comment by RemiAllio** [comment]
Great ! 🙂
