### ISSUE TITLE
Add annotations to assembled mitogenomes

### ISSUE THREAD

**Issue by csmiguel** [RemiAllio/MitoFinder#3]
Great tool,
I have several mitogenomes already assembled belonging to mammals. I wonder if I could use MitoFinder to do the annotations and formatting for GenBank. What would the command look like?

Thanks a lot !

**Comment by RemiAllio** [comment]
Hi,

So, the first thing to do is to download reference mitochondrial genomes from NCBI. The procedure is described [here](https://github.com/RemiAllio/MitoFinder#how-to-get-reference-mitochondrial-genomes-from-ncbi). 
In your case, I think the best would be to download all the RefSeq mitochondrial genomes available for mammals. Be sure to select "mitochondrion" and "RefSeq" and specify a range size of 10,000 to 20,000 bp. You should find 1153 mitochondrial genomes for mammals. Mitofinder will select the best one for each of your species.  
  
Then, the command should look like (for each mitogenome):  
/path/to/mitofinder/mitofinder -j [sequence_id] -a [mitogenome.fasta] -r [genbank_reference.gb] -o [genetic_code] -p [threads] -m [memory] -n 5  
  
(replace the square brackets with the appropriate values (without the square brackets))  
  
The -n option is important for mammals. Indeed, MitoFinder makes blast annotations at the amino acid level. Then, at the codon level, it looks for start and stop codons. However, in mammals, some mitochondrial genes does not have stop codons. So the value of the -n option must be small.   
  
MitoFinder should run in few seconds/minutes.  
  
If you want to submit your annotated mitogenomes to genbank you will need to use either bankit or tbl2asn.  
The procedure is explained [here](https://github.com/RemiAllio/MitoFinder#how-to-submit-your-annotated-mitochondrial-genomes-to-ncbi-genbank).  

Before to submit, I really encourage you to check the annotation anyway.  

I hope this and MitoFinder could help you!  
Best,  
Rémi

**Comment by csmiguel** [comment]
Fantastic! Thanks so much for your answer and for developing this great tool! I will follow your instructions.
