### ISSUE TITLE
Annotating error

### ISSUE THREAD

**Issue by luishdez35** [RemiAllio/MitoFinder#31]
Error when I run: `mitofinder -j Phidippus_adonis_DGF0948 -a Phidippus_adonis_DGF0948.contigs.fasta -r Habronattus_oregonensis_genome.gb -o 5 -p 4 -m 8`

Some advice? 

`Traceback (most recent call last):
  File "/opt/anaconda3/envs/mitofinder/bin/mitofinder", line 1139, in <module>
    if check_if_string_in_file(pathtowork + "/geneChecker.log","MiTFi failed.") or (os.stat(pathOfFinalResults+"MiTFi.log").st_size != 0 and not check_if_string_in_file(pathOfFinalResults+"MiTFi.log","hits")) :
OSError: [Errno 2] No such file or directory: '/Users/luiscarloshernandez/Desktop/UCEs-Phidippus/Analysis/Mitofinder analisis/Phidippus_adonis_DGF0948/Phidippus_adonis_DGF0948_MitoFinder_mitfi_Final_Results/MiTFi.log'
(mitofinder) luiscarloshernandez@MacBook-Air-de-Luis Mitofinder analisis % mitofinder -j Phidippus_adonis_DGF0948_CO1 -a Phidippus_adonis_DGF0948.contigs.fasta -r COI_reference_Phidippus.gb -o 5 -p 4 -m 8`

Thanks a lot

**Comment by RemiAllio** [comment]
Hi !

I can see that you are using the anaconda version of MitoFinder. I don't know who created this version but it's not me ...

My advice would be to install MitoFinder following one of the official installation procedures proposed [here](https://github.com/RemiAllio/MitoFinder#installation-guide-for-mitofinder). 

Sorry for the inconvenience,
Best regards,
Rémi

**Comment by luishdez35** [comment]
Thanks for the reply RemiAllio, I try you suggestion, but I have the same error. 

`Traceback (most recent call last):
  File "/Users/luiscarloshernandez/MitoFinder/mitofinder", line 1139, in <module>
    if check_if_string_in_file(pathtowork + "/geneChecker.log","MiTFi failed.") or (os.stat(pathOfFinalResults+"MiTFi.log").st_size != 0 and not check_if_string_in_file(pathOfFinalResults+"MiTFi.log","hits")) :
OSError: [Errno 2] No such file or directory: '/Users/luiscarloshernandez/Desktop/UCEs-Phidippus/Analysis/Mitofinder analisis/Phidippus_adonis_DGF0948/Phidippus_adonis_DGF0948_MitoFinder_mitfi_Final_Results/MiTFi.log'`

It seems that mitfi can't write the log file, and it doesn't give me the output files that it should.

Thanks for your support

**Comment by luishdez35** [comment]
SOLVED, 
I put the contigs inside the folder test_case in Mitofinder directory, and work fine, I don't know why in others directory doesn't work,
