### ISSUE TITLE
Problem with creating summary statistics for the mtDNA contig

### ISSUE THREAD

**Issue by sallesmath** [RemiAllio/MitoFinder#32]
Hello Remi!

I have been trying to run MitoFinder directly on a previously computed assembly via phyluce, and all works well until I receive the following error:

```
Command line: /home/sallesmath/MitoFinder/mitofinder -j amcc204510 -a amcc204510.contigs.fasta -r sequence.gb -o 2 -p 4

Now running MitoFinder ...

Start time : 2022-04-15 15:19:16

Job name = amcc204510

Creating Output directory : /home/sallesmath/dados_uce/phyluce_dados_uce_tropidurus/mitofinder/amcc204510
All results will be written here

Program folders:
MEGAHIT = /home/sallesmath/MitoFinder/megahit/
MetaSPAdes folder = /home/sallesmath/MitoFinder/metaspades/bin/
IDBA-UD folder = /home/sallesmath/MitoFinder/idba/bin/
Blast folder = /home/sallesmath/ncbi-blast-2.13.0+/bin/
ARWEN folder = /home/sallesmath/MitoFinder/arwen/
MiTFi folder = /home/sallesmath/MitoFinder/mitfi/
tRNAscan-SE folder = /home/sallesmath/MitoFinder/trnascanSE/tRNAscan-SE-2.0/

Formatting database for mitochondrial contigs identification...
Running mitochondrial contigs identification step...

MitoFinder found a single mitochondrial contig
Checking resulting contig for circularization...

Evidences of circularization could not be found, but everyother step was successful

Creating summary statistics for the mtDNA contig
Traceback (most recent call last):
  File "/home/sallesmath/MitoFinder/mitofinder", line 1020, in <module>
    rename = Popen(args1, stdout=open(os.devnull, 'wb'))
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

It seems that there's something causing an error in the annotation step. I get final the mtDNA contig found by MitoFinder, but there is just one file present in the final results folder (.info).

I'm not sure what the cause of this error is. Any suggestions?

Best regards,
Matheus.

**Comment by RemiAllio** [comment]
Hello Matheus,

Sorry for the late replay...

Unfortunately I'm not sure I have an "easy" fix for this case. 
The error may be due to a permission problem in your computer. 
I need more information. 

Is there anything written in the .info file?

Could you confirm that the file /home/sallesmath/MitoFinder/rename_fasta_seqID.py exists? Is it executable? (you can make it executable using ```chmod 764 /home/sallesmath/MitoFinder/rename_fasta_seqID.py ```)

Also, can you find a file named "amcc204510.fasta" somewhere?

Sorry for the inconvenience,
Cheers,
Rémi

**Comment by sallesmath** [comment]
No problem, thanks for the reply!

For example, when I open the file "amcc204510_mtDNA_contig_1.infos", at /home/sallesmath/dados_uce/phyluce_dados_uce_tropidurus/mitofinder/amcc204510/amcc204510_MitoFinder_mitfi_Final_Results/, this is what I got:

```
Statistics for contig 1:

Initial contig name: NODE_6_length_3596_cov_4.649534
Length: 3596
GC content: 43.63%
Circularization: NA
```

Also, I made the rename_fasta_seqID.py file executable, and changed the name of "amcc204510.contigs.fasta" to "amcc204510.fasta". But the problem remains the same, unfortunately.

**Comment by RemiAllio** [comment]
Hi,

Which version of MitoFinder do you use?

Is it possible for you to use the [singularity image of MitoFinder](https://github.com/RemiAllio/MitoFinder#run-mitofinder-with-singularity)?
If not, we will try to figure out what is going on but may be the easiest way to use MitoFinder in your case would be to use singularity 🤔 

Cheers,
Rémi

**Comment by sallesmath** [comment]
It all worked out running through the singularity image of MitoFinder.

Thanks Rémi

**Comment by RemiAllio** [comment]
Nice!

The issue was certainly from a permission error somewhere in your environment which is quite difficult to manage for me remotely.

Sorry again for the inconvenience,
Best,
Rémi
