### ISSUE TITLE
Problem running the program

### ISSUE THREAD

**Issue by luishdez35** [RemiAllio/MitoFinder#37]
Hello, I try to run again MItofinder, but I have the next problem:

`Traceback (most recent call last):
  File "/opt/anaconda3/envs/mitofinder2/bin/MitoFinder/mitofinder", line 1209, in <module>
    rename = Popen(args1, stdout=open(os.devnull, 'wb'))
  File "/opt/anaconda3/envs/mitofinder2/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/opt/anaconda3/envs/mitofinder2/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

The program seems to found contigs but doesn't finish

I hope you can help me with this, I ran Mitofinder last year without problems

Best

**Comment by luishdez35** [comment]
Hello Remi, 
Yes, I am using python 2.7 in my conda environment; I will try the singularity container, I don how to use it, but I figure it out. 

Best

**Comment by RemiAllio** [comment]
Please see [Run MitoFinder with Singularity](https://github.com/RemiAllio/MitoFinder#run-mitofinder-with-singularity) and let me know if I can help you!

**Comment by luishdez35** [comment]
Perfecto, I will do that. 

Thanks

**Comment by RemiAllio** [comment]
Sorry again for the inconvenience ...

**Comment by luishdez35** [comment]
Work perfect running with Singularity, thanks. 

Best

**Comment by RemiAllio** [comment]
Nice! Thanks for your feedback 🙂
