### ISSUE TITLE
Issue running current version 

### ISSUE THREAD

**Issue by ellieearmstrong** [RemiAllio/MitoFinder#4]
Hi there!

I am getting an issue with the current installation. The assembly step runs absolutely fine, but when I try to run the numt identification step on the contigs from the first step I get this error:

```
Traceback (most recent call last):
  File "/scratch/PI/dpetrov/armstrong/applications/MitoFinder/mitofinder", line 1249, in <module>
    fifthStep = Popen(args1, cwd=pathOfFinalResults, stdout=open('geneChecker.log', 'a'), stderr=open('geneChecker_erreur.log', 'a'))
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
I have tried it on multiple different systems and using git clone/etc, so I think it may be something to do with the python script being solved, but please let me know if you have any ideas!

Here is my code:
`//MitoFinder/mitofinder -j sample1-numt-test1 -a sample1-mito-test1_link_megahit.scafSeq -r refsample.gb -o 2 -p 40 --numt --nwalk 0`

Thank you so much!

**Comment by RemiAllio** [comment]
Hi!

I just released the new version of MitoFinder (v1.3) in which this problem should be solved!
Please, let me know if this is not the case.

Thank you for your feedback and comment!
Cheers,
Rémi
