### ISSUE TITLE
blast problem on ubuntu 22.04

### ISSUE THREAD

**Issue by benoitnabholz** [RemiAllio/MitoFinder#44]
Hi Remi,

I have a problem with the makeblastdb available with MitoFinder on ubuntu 22.04:
MitoFinder/blast/bin/makeblastdb: error while loading shared libraries: libidn.so.11: cannot open shared object file: No such file or directory

I tried made a symbolic link my version of blast but the pipeline doesn't work and I fear it could be because of that (not sure).

Cheers,
Benoit

**Comment by RemiAllio** [comment]
Hi Benoit,

Could you please try to specify the path of your blast executables in the MitoFinder config file (```Mitofinder.config```) instead of creating a symbolic link?
Do you confirm that your executable works outside MitoFinder? I guess so, but just to be sure...
If not, you will need to install the libidn.so.11 library (you can try ```sudo yum install libidn.x86_64```).

Finally, you still can try the singularity container of MitoFinder :slightly_smiling_face:

Cheers,
Rémi

**Comment by benoitnabholz** [comment]
Hi Rémy,

Singularity is working very well. I just wanted to let you know some issue with ubuntu 22.04. 
So the problem doesn't come makeblastdb as putting the path in Mitofinder.config solves the problem. 
I still have this error:

Creating summary statistics for mtDNA contig 1

Traceback (most recent call last):
  File "/home/benoitnabholz/softwares/MitoFinder/mitofinder", line 1209, in <module>
    rename = Popen(args1, stdout=open(os.devnull, 'wb'))
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

And nothing is in the folder *_MitoFinder_arwen_Final_Results except the *.infos file.


Benoit

**Comment by benoitnabholz** [comment]
So the problem seems to be the same as here: https://github.com/RemiAllio/MitoFinder/issues/41 
Since singularity is working, it is not urgent at all.

**Comment by RemiAllio** [comment]
Nice, well spotted! 
I need to translate the scripts in python 3. One day...
Cheers!
Rémi

**Comment by Isoris** [comment]
conda / mamba create -n mitofinder_env python=2.7

cd MitoFinder

which python2.7 

then use sed 

sed -i 's|#!/usr/bin/python2|#!ADDTHEPATHHERE|' mitofinder

**Comment by AlcaArctica** [comment]
This helped me as well! Thank you
