### ISSUE TITLE
mitofinder installation

### ISSUE THREAD

**Issue by gubrins** [RemiAllio/MitoFinder#49]
Hi,
I succesfully installed mitofinder in an old computer but I am trying in a new one and it is not working. I tried to use singularity but I did not manage. 
I have created a new conda environment with python2.7 and mitofinder:
`conda create -n mitofinder -c bioconda mitofinder python=2.7`

but when trying to run the program, I get this message:

```
/home/goliath/miniconda3/envs/mitofinder2/lib/python2.7/site-packages/Bio/SearchIO/__init__.py:211: BiopythonExperimentalWarning: Bio.SearchIO is an experimental submodule which may undergo significant changes prior to its future official release.
  BiopythonExperimentalWarning)

Command line: /home/goliath/miniconda3/envs/mitofinder2/bin/mitofinder -j 12953 -1 /mnt/DiscoA/cerastes/raw_data/wgs/filtered/12953_filtered_1.fastq.gz -2 /mnt/DiscoA/cerastes/raw_data/wgs/filtered/12953_filtered_2.fastq.gz -r Vip_berus_mito.gb -o 2 -p 40 -m 80 --override

Now running MitoFinder ...

Start time : 2023-06-07 15:20:30

Job name = 12953

ERROR: MitoFinder is not installed.
No such file or directory: /home/goliath/miniconda3/envs/mitofinder2/bin/install.sh.ok
Please run ./install.sh in the MitoFinder directory.
Aborting.

```
Do you know what's going on?

Thanks in advance!

**Comment by RemiAllio** [comment]
Hi, 

Thank you for contacting me. 

If you have installation permissions in your computer, why not installing MitoFinder with the standard procedure? Meaning downloading the git repository and run install.sh. 
Then, you might need to replace the first line of MitoFinder and each .py file of the repository to ask the program to specifically use python2.7. 
The line to write is as follows:
#!/usr/bin/python2
Corresponding to by "#!"+the path to python 2 or python2.7 in your system (you can find the path using `which python2.7`)

Let me know if it helps and sorry for the inconvenience…
Best,
Rémi

**Comment by gubrins** [comment]
Thanks for the quick answer, that worked!!!
