### ISSUE TITLE
Installation problem related to megahit

### ISSUE THREAD

**Issue by hector-romao** [RemiAllio/MitoFinder#59]
Hello
I have installed MitoFinder through the singularity conatiner as recommended.

When i run the test data, the assembly step is not completed due MEGAHIT.
The following command was used:

```
../../programas/mitofinder_v1.4.2.sif -j Aphaenogaster_megommata_SRR1303315 -1 Aphaenogaster_megommata_SRR1303315_R1_cleaned.fastq.gz -2 Aphaenogaster_megommata_SRR1303315_R2_cleaned.fastq.gz -r reference.gb -o 5 -p 5 -m 10

``` 
This give me the following message:
 ERROR: MEGAHIT didn't run well
Please check log file : /media/lgbio-nas1/hectorromao/MitoFinder_container/test_case/Aphaenogaster_megommata_SRR1303315/megahit.log

With the log that contains the message:

2024-06-04 11:10:04 - MEGAHIT v1.2.7
2024-06-04 11:10:04 - Using megahit_core with POPCNT and BMI2 support
Traceback (most recent call last):
  File "/opt/MitoFinder/megahit/megahit", line 1013, in <module>
    main()
  File "/opt/MitoFinder/megahit/megahit", line 963, in main
    build_library()
  File "/opt/MitoFinder/megahit/megahit", line 258, in checked_or_call
    func(*args, **kwargs)
  File "/opt/MitoFinder/megahit/megahit", line 700, in build_library
    create_fifo('pe1', i, inpipe_cmd(opt.pe1[i]))
  File "/opt/MitoFinder/megahit/megahit", line 687, in create_fifo
    os.mkfifo(fifo_path)
    
   I've already tried to use another installation executable of MEGAHIT bia the config file
   
   
```
../../programas/mitofinder_v1.4.2.sif -j Aphaenogaster_megommata_SRR1303315 -1 Aphaenogaster_megommata_SRR1303315_R1_cleaned.fastq.gz -2 Aphaenogaster_megommata_SRR1303315_R2_cleaned.fastq.gz -r reference.gb -o 5 -p 5 -m 10 -c Mitofinder.config  --override
``` 

But again an error message is given, this time describing: 

/bin/sh: 1: /home/lgbio/programas/MitoFinder/megahit/build/megahit: not found

Which is strange, because the program is installed in this folder
$ which megahit
/home/lgbio/programas/MitoFinder/megahit/build/megahit

**Comment by RemiAllio** [comment]
Hi,

Thank you for your message and sorry for the inconvenience. 

Can you try the following command:
```singularity run --bind  /home/lgbio/programas/MitoFinder/megahit/build/ ../../programas/mitofinder_v1.4.2.sif -j Aphaenogaster_megommata_SRR1303315 -1 Aphaenogaster_megommata_SRR1303315_R1_cleaned.fastq.gz -2 Aphaenogaster_megommata_SRR1303315_R2_cleaned.fastq.gz -r reference.gb -o 5 -p 5 -m 10```

**Comment by hector-romao** [comment]
Thanks for the quick reply
I tried but got the same error.
I assume the error is related to creating fifo files, which my server does not support.

Is there a way to set up a temporary dir to run the analysis?

**Comment by RemiAllio** [comment]
Okay so you got the error with the two megahit executables right?

If so, it may comes from write permissions indeed. It is not possible to set up a temporary directory but you can run the analyses from wherever you want (you don't need to be at the same place as your files). So if you have permissions in another directory, you may want to run the analysis from there. Is it something possible for you? Would it help?

**Comment by hector-romao** [comment]
Yes.
This was a good workaround.
Thanks for your attention.
