### ISSUE TITLE
[Seq_ID]_mtDNA_contig.png not created

### ISSUE THREAD

**Issue by AkshitaJain2709** [RemiAllio/MitoFinder#63]
Hello,

The output from MitoFinder is giving all the files except [Seq_ID]_mtDNA_contig.png schematic representation of the annotation of the mtDNA contig. Could you please let me know how can I extract that file. 
Thanks

**Comment by AkshitaJain2709** [comment]
Dear Remi

Thanks for your reply.

I am getting the following message: 

Organism type specified: 1
alignCutOff: 30.0
coveCutOff: 7
Checking protein-coding genes, tRNAs and rRNAs from reference with organismType=1...
Formatting database for blast...
Formatting database for blast...
rrnL
rrnS
Features found: 13
Total features: 14

Running tRNA annotation with mitfi
Total features found after mitfi:  28

Could not import Image or ImageDraw library, no image of result being created.
tRNA-Asp = 8497,8561
ND5 = 8281,9021

Should I install any dependency?

Thanks

**Comment by RemiAllio** [comment]
Yes you would need to install pillow.

Here is the way I do it during the singularity image creation:
```
wget  https://bootstrap.pypa.io/pip/2.7/get-pip.py  
python2.7 get-pip.py  
pip2.7 install pillow==6.2.2  
```

Hope this helps!
Best,
Rémi

**Comment by RemiAllio** [comment]
Hi,

Does it work now?

Best,
Rémi

**Comment by AkshitaJain2709** [comment]
Dear Remi

It didn’t work, but I imported the gff file in Geneious prime for visualisation. Thanks for your help, really appreciate it.


Thanks,
Akshita


Akshita Jain (she/her) | PhD Candidate | Plant Pathology

School of Applied Systems Biology | La Trobe University

AgriBio Centre | Agriculture Victoria Research | Department of Jobs Precincts and Regions

5, Ring Road, La Trobe University, Bundoora, VIC 3083

T: 9032 7129| M: 0452499270 | E: ***@***.******@***.***>



[Image]

We work flexibly at Agriculture Victoria Research. I am sending this message now because this time suits me, and I encourage you to read, respond or action this email at a time that best works for you.



OFFICIAL

________________________________

**Comment by RemiAllio** [comment]
Oh, sorry for the inconvenience... IMO the best option would have been to use the singularity container to obtain the png from MitoFinder. But the geneious visualization tool is good so hopefully it works for you like that!

Best,
Rémi
